Add workflow for Trend Micro Vision One API #66
ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API pull request #67
Opened 2021-09-17 14:27 UTC by Fa6s

I am SIEM consultant for IBM Security Germany who wrote this workflow to help one of his clients ingesting the Trend Micro Vision One alert events.

2021-09-28 13:18 UTC, ChrisCollinsIBM requested changes

2021-09-28 13:18 UTC, ChrisCollinsIBM commented on Trend Micro Vision One/TrendMicroVisionOne-Parameter-Values.xml
> +  <Value name="baerer_token"      value="" />
Can you update this throughout the workflow to "bearer_token" please? Thank you.

2021-09-28 13:18 UTC, ChrisCollinsIBM commented on Trend Micro Vision One/TrendMicroVisionOne-Workflow.xml
> +        <Parameter name="baerer_token" label="baerer_token" required="true" secret="true" />
Looks like there's some mixed tab/space indentation here in the 2 `Parameter` tags

2021-09-28 13:18 UTC, ChrisCollinsIBM commented on Trend Micro Vision One/TrendMicroVisionOne-Workflow.xml
> +			<Set value="&lt;191&gt;1 ${/endDateTime} ${/logSourceIdentifier} LEEF:2.0|IBM|Trend Micro Vision One|1.0|" path="/syslogHeaderPart1"/>
It looks like you're trying to create an RFC5424 syslog payload here which is great! But for it to be compliant you'll need to add the placeholders for APP-NAME, PROCID and MSGID. 

Usually you'll just see these as `- - -` after the hostname and before the structured data (the actual payload).

Right now this will generate a payload like

`<191>1 2021-09-01T13:13:13Z myidentifier.com LEEF:2.0|IBM|Trend Micro Vision One|1.0|......`
Where you'll want it to be
`<191>1 2021-09-01T13:13:13Z myidentifier.com - - - LEEF:2.0|IBM|Trend Micro Vision One|1.0|......` to be RFC5424 compliant.

https://tools.ietf.org/html/rfc5424

2021-09-28 13:18 UTC, ChrisCollinsIBM commented on Trend Micro Vision One/TrendMicroVisionOne-Workflow.xml
> +		<FormatDate pattern="yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" timeZone="UTC" time="${time()}" savePath="/current_Time" />
`yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` is re-used in a lot of places, have you considered making into a variable instead and re-using it that way?

2021-09-28 13:18 UTC, ChrisCollinsIBM commented on Trend Micro Vision One/TrendMicroVisionOne-Workflow.xml
> +<Workflow name="Test" version="1.0" xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V2">
It would be good to have the workflow name set rather than "Test"

2021-09-28 13:18 UTC, ChrisCollinsIBM commented on Trend Micro Vision One/README.md
> +- Input Parameters:
Excellent readme, thank you!

2021-09-28 15:20 UTC, Fa6s commented on Trend Micro Vision One/TrendMicroVisionOne-Workflow.xml
> +<Workflow name="Test" version="1.0" xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V2">
Done

2021-09-28 15:20 UTC, Fa6s commented on Trend Micro Vision One/TrendMicroVisionOne-Workflow.xml
> +		<FormatDate pattern="yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" timeZone="UTC" time="${time()}" savePath="/current_Time" />
Done

2021-09-28 15:20 UTC, Fa6s commented on Trend Micro Vision One/TrendMicroVisionOne-Workflow.xml
> +			<Set value="&lt;191&gt;1 ${/endDateTime} ${/logSourceIdentifier} LEEF:2.0|IBM|Trend Micro Vision One|1.0|" path="/syslogHeaderPart1"/>
Done

2021-09-28 15:21 UTC, Fa6s commented on Trend Micro Vision One/TrendMicroVisionOne-Parameter-Values.xml
> +  <Value name="baerer_token"      value="" />
Done

2021-09-29 01:32 UTC, ChrisCollinsIBM approved these changes

2021-09-29 01:32 UTC, merged