Add Mulesoft Workflow #52
ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API pull request #68
Opened 2021-09-27 19:35 UTC by adamdcameron

2021-09-28 13:27 UTC, ChrisCollinsIBM requested changes

2021-09-28 13:27 UTC, ChrisCollinsIBM commented on Mulesoft/Mulesoft_Workflow_Parameters.xml
> +	<Value name="orderByDate" value="DESC" />
Is `orderByDate` something that would change? I wouldn't think it would but wanted to ask.

Usually in the workflow parameters we put things that possibly need configuration on a case-by-case basis, and anything that you just want to use as a variable instead you would put in the main workflow.

2021-09-28 13:34 UTC, ChrisCollinsIBM requested changes

2021-09-28 13:34 UTC, ChrisCollinsIBM commented on Mulesoft/README.md
> +- Host (Customer Endpoint URL)
This is actually more "Customer Endpoint Hostname" rather than URL from what I can see, since we're building the URL in the workflow. Just want to make sure it's clear to the user that it's a hostname and not a URL they should enter in their parameter.

2022-01-21 14:48 UTC, ChrisCollinsIBM commented
Hi @adamdcameron, just wanted to follow up on the changes requested for this pull request.

When you have a chance if you could have a look at the changes requested we'd love to get things merged in. Thanks!

2022-01-21 15:31 UTC, adamdcameron reviewed
Looks fine to me, this should work for customers.

2022-01-21 18:46 UTC, adamdcameron commented on Mulesoft/Mulesoft_Workflow_Parameters.xml
> +	<Value name="orderByDate" value="DESC" />
Yeah, you could comment this into the workflow itself I suppose.

2022-01-21 18:47 UTC, adamdcameron commented on Mulesoft/README.md
> +- Host (Customer Endpoint URL)
That sounds better, use "Hostname"

2022-01-24 14:40 UTC, ChrisCollinsIBM commented
Thanks for the updates @adamdcameron !

2022-01-24 14:40 UTC, ChrisCollinsIBM approved these changes

2022-01-24 14:41 UTC, merged