Add Wiz workflow #80
ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API pull request #81
Opened 2021-12-30 12:55 UTC by solalraveh

@rbl-itay FYI

2022-01-05 14:51 UTC, ChrisCollinsIBM requested changes
Overall things look very well done, nicely organized, formatted, and cleanly laid out.

I did have a few comments to have a look at that won't block an initial merge, but if you'd like to comment or address them first I'd be happy to discuss any feedback you have around them.

Thanks for the submission!

2022-01-05 14:51 UTC, ChrisCollinsIBM commented on Wiz/.gitignore
> +# General
.gitignore files should not be checked in

2022-01-05 14:51 UTC, ChrisCollinsIBM commented on Wiz/Wiz-Workflow-Parameter-Values.xml
> +    <Value
Would you be expecting users to modify the query?

If not you might want to define the query in the workflow itself as the Parameter Values is usually more meant for secrets and config values. 

But if it's meant to be modified then here is fine as well.

2022-01-05 14:51 UTC, ChrisCollinsIBM commented on Wiz/Wiz-Workflow-Parameter-Values.xml
> +    <Value name="historical_days" value="10" />
consider changing this to "initial_historical_days" as this is only ever used on the very first run.

2022-01-05 15:38 UTC, solalraveh commented on Wiz/.gitignore
> +# General
@ChrisCollinsIBM I can remove it, but wanted to avoid any local cache or Mac file checking in for no reason. Are you OK with leaving it, or remove any way?

2022-01-05 15:43 UTC, solalraveh commented on Wiz/Wiz-Workflow.xml
> +            <Set path="/bookmark" value="${/current_time}" />
@ChrisCollinsIBM You'll see in line 21 that the timestamp is saved at the beginning.
The first call uses that timestamp (43-64). 
We then paginate and what counts is the end cursor, while we still look for "timestamp", which was set when the workflow launched (line 21).

What's saved to "current_time" is the dump at the current pass of issues from Wiz (batches of 500)., but we won't miss any from being pulled, due to what I described above ^^. I hope this helps.

2022-01-05 15:43 UTC, ChrisCollinsIBM commented on Wiz/.gitignore
> +# General
Usually you'd use a .gitignore file to ignore any artifacts generated by the project itself, tmp files, build artifacts, etc.

For projects like this that aren't a full Eclipse or IntelliJ project or anything we'd prefer to leave them out - thanks!

2022-01-05 15:44 UTC, solalraveh commented on Wiz/Wiz-Workflow-Parameter-Values.xml
> +    <Value
It leaves an opening for changing. Some rare cases would change it to get more or less fields in the Issues that are fetched.
That led to the decision to mark it as value. Does it make sense?

2022-01-05 15:46 UTC, solalraveh commented on Wiz/Wiz-Workflow-Parameter-Values.xml
> +    <Value name="historical_days" value="10" />
ACK. I've put it in f5b04e2385bbf96fddebe99ae4a08744b970e465

2022-01-05 15:47 UTC, solalraveh commented on Wiz/.gitignore
> +# General
ACK. NP. It's in 69e5cf6f05bcfeea3a67d7a17955a5a8aca22ec5

2022-01-05 15:49 UTC, ChrisCollinsIBM commented on Wiz/Wiz-Workflow.xml
> +            <Set path="/bookmark" value="${/current_time}" />
I understand the pagination aspect, it's not that I'm worried about, it's the timestamp used between runs that I'm concerned about.

When you're completely finished this run you're going to set the bookmark timestamp on line 79 to the current system time, or you'll do it on line 124 if there are subsequent pages. When you run again later (1 minute, 5 minutes, whatever it's set for) that's the timestamp things will be initialized at. This leaves a possibility for events that weren't seen on the last execution loop since they didn't come back in the initial query but have a createdAt timestamp of before the current system time.

We've seen this pitfall in a lot of pre-development of integrations we've done which is why we try to extract timestamps from the events themselves to use as the boundary for query on the next batch instead of using a system time.

2022-01-05 15:52 UTC, solalraveh commented on Wiz/Wiz-Workflow.xml
> +            <Set path="/bookmark" value="${/current_time}" />
Got it. Let me have a look.

2022-01-07 12:47 UTC, solalraveh commented on Wiz/Wiz-Workflow.xml
> +            <Set path="/bookmark" value="${/current_time}" />
Hi @ChrisCollinsIBM the changes have been made and are in b4db565b84d87b8014e46b5fbcfd2dae304b60ef

2022-01-11 10:38 UTC, rbl-itay commented
Hi @ChrisCollinsIBM, is there an update on the PR? can it be merged?

2022-01-11 13:06 UTC, ChrisCollinsIBM commented on Wiz/Wiz-Workflow.xml
> +            <If condition="/current_event_time + 1000 > /bookmark" >
This looks great, bookmark is initialized originally with the initial_historical_offset and then if we get some timestamps from events that are greater than that we update. Then on subsequent runs we only update the bookmark IF newer events come in.

Do you know if the ` "after": "${/timestamp}"` filter is after or after and including? `( > or >= )`.  If after 12:00:00 for example includes 12:00:00 `( > = )` then the padding of the bookmark with the `+ 1000` would be needed to push it 1 second ahead as you've done. If after does NOT include the requested timestamp `( > )`

Just want to make sure you're not adding a spot where there could be a 1 second gap in possible event collection in case after is truly after and not "after and including".

I'll merge it either way but just wanted to note that!

2022-01-11 13:08 UTC, ChrisCollinsIBM approved these changes
Bookmark timestamp updates look great - thank you!

2022-01-11 13:08 UTC, merged

2022-01-11 13:09 UTC, solalraveh commented on Wiz/Wiz-Workflow.xml
> +            <If condition="/current_event_time + 1000 > /bookmark" >
Thanks for the note. I'll verify, but it should be just similar to `>`