Add Sophos Central workflow #83
ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API pull request #84
Opened 2022-01-10 16:18 UTC by garyjohn-pps

Workflow templates for Sophos Central.

2022-01-11 13:23 UTC, ChrisCollinsIBM requested changes
Thanks for the submission.

I had a few questions and comments you'll find within the review - thanks!

2022-01-11 13:23 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow.xml
> +            <QueryParameter name="from_date" value="${/bookmark}" />
On a first run this value will be blank based on the current line 13 initialization.

Would you be expecting users to take action on line 13 with an example from line 12 before deploying this? And if they don't will the API call succeed and pull ALL available historical data or will it fail from it not being a valid `from_date` ?

2022-01-11 13:23 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow.xml
> +            <QueryParameter name="limit" value="1000" omitIfEmpty="true" />
Since there is a limit in place here then the API must provide some type of paging mechanism, I don't see anything here to handle subsequent pages so just wondering if that's something you were planning on implementing in the future?

If it is planned for the future the sections should probably get some comments around them for future TODO actions just so there isn't an implied level of completeness inferred.

2022-01-11 13:23 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow.xml
> +      <SSLHandshakeTest host="${/region_api_host}" />
Looks like some spaces made it in here instead of tabs for indentation. Either is fine but it's good to keep them consistent.

2022-01-11 13:23 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow-Parameter-Values.xml
> +    <Value name="global_api_host"   value="api.central.sophos.com" />
This doesn't appear to be used in the workflow, is it still required?

2022-01-11 13:23 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow-Parameter-Values.xml
> +    <Value name="region_api_host"   value="api-eu01.central.sophos.com" />
Perhaps this should just be `api_host` and the end user can decide whether or not to use a global or regional API endpoint?

A note in the readme or in a comment above this value may help end users choose what to put in with a pointer to the Sophos docs
https://developer.sophos.com/intro#global-vs-regional-apis

2022-01-11 15:58 UTC, garyjohn-pps commented on Sophos Central/SophosCentral-Workflow.xml
> +      <SSLHandshakeTest host="${/region_api_host}" />
Indentation is now tabs throughout in the updated Workflows.

2022-01-11 15:59 UTC, garyjohn-pps commented on Sophos Central/SophosCentral-Workflow-Parameter-Values.xml
> +    <Value name="global_api_host"   value="api.central.sophos.com" />
It is not required. The "global_api_host" workflow parameter will be removed from the templates.

2022-01-11 16:08 UTC, garyjohn-pps commented on Sophos Central/SophosCentral-Workflow-Parameter-Values.xml
> +    <Value name="region_api_host"   value="api-eu01.central.sophos.com" />
Agree. Have updated the templates switching to "api_host" as suggested.
Have also added a note to the Readme file with details about the API Host values.

2022-01-11 17:09 UTC, garyjohn-pps commented on Sophos Central/SophosCentral-Workflow.xml
> +            <QueryParameter name="limit" value="1000" omitIfEmpty="true" />
Yes, pagination would be an enhancement to add for the future. Sophos Central provides a "cursor" query parameter but this was not something that was utilised at the time due to a low volume of events in the customer's environment.
Will add some TODO comments around pagination to the workflow template.

2022-01-11 17:12 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow-Parameter-Values.xml
> +    <Value name="region_api_host"   value="api-eu01.central.sophos.com" />
Great, thanks!

2022-01-11 18:01 UTC, garyjohn-pps commented on Sophos Central/SophosCentral-Workflow.xml
> +            <QueryParameter name="from_date" value="${/bookmark}" />
For now, the user should provide a value for the initial bookmark which needs to be a Unix timestamp within the last 24 hours. Sophos Central doesn't retrieve anything older than 24 hours.
Have updated the Readme.md file with more details. 
As an enhancement I will look to see if I can incorporate the echo logic into the Initialize statement.

2022-01-12 11:21 UTC, garyjohn-pps commented
Thanks for the feedback Chris.
Per your suggestions, I have updated the templates and readme file.
Please let me know if there's anything else needed.

2022-01-13 19:45 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow.xml
> +            <QueryParameter name="from_date" value="${/bookmark}" />
Have a look at this Workflow that was recently merged and specifically how the bookmark is initialized on the first try

https://github.com/ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API/blob/master/Wiz/Wiz-Workflow.xml#L15

You just do a similar method of picking a default number of hours to go back like this workflow does with the historical days, or you can just default to "12 hours ago" or something similar in the calculation offset.

2022-01-17 10:41 UTC, garyjohn-pps commented on Sophos Central/SophosCentral-Workflow.xml
> +            <QueryParameter name="from_date" value="${/bookmark}" />
Agree. Have made the update to the initial bookmark as suggested. Due to Sophos requiring a Unix timestamp in seconds (not milliseconds) I had to use the substring function to get the value in the correct format for the API call.

2022-01-17 13:27 UTC, ChrisCollinsIBM commented on Sophos Central/SophosCentral-Workflow.xml
> +            <QueryParameter name="from_date" value="${/bookmark}" />
Substring works, I'm guessing divide by 1000 probably ends up leaving you with a decimal place so stripping the last 3 digits off is a great solution.

2022-01-17 13:30 UTC, ChrisCollinsIBM approved these changes

2022-01-17 13:32 UTC, ChrisCollinsIBM commented
Thanks for taking a second look at some of these items @garyjohn-pps, initial workflow was good but with these additional tweaks I think it's a great submission for users looking to integrate with this product.

Thanks again!

2022-01-17 13:32 UTC, merged